// Datos de obras — Hevi Art, Barcelona
// Categorías: oleo, carboncillo, acuarela, acrilico, tinta, digital
window.ARTWORKS = [
  {
    id: "o-001",
    title: "Ventana en silencio",
    series: "Notas de taller",
    year: 2024,
    category: "oleo",
    technique: "Óleo sobre lienzo",
    w: 80, h: 100,
    priceEUR: 2400,
    sold: false,
    featured: true,
    img: "https://images.saatchiart.com/saatchi/673178/art/13502235/12564367-EHVXRXBR-7.jpg",
    desc: "El rastro de una tarde en que la luz del norte entra al taller. Polvo acumulado en el alféizar, últimas capas en la paleta.",
  },
  {
    id: "c-002",
    title: "Madre — Tres estudios",
    series: "Retratos",
    year: 2023,
    category: "carboncillo",
    technique: "Grafito y carboncillo sobre papel",
    w: 42, h: 59,
    priceEUR: 850,
    sold: false,
    featured: true,
    img: "https://images.saatchiart.com/saatchi/688433/art/11064481/10126765-IOYTWNBJ-7.jpg",
    desc: "Tres poses, estudios de diez minutos. La línea temblorosa, la mirada firme.",
  },
  {
    id: "a-003",
    title: "Mediterráneo, mañana",
    series: "Cuaderno de costa",
    year: 2024,
    category: "acuarela",
    technique: "Acuarela sobre papel de algodón",
    w: 38, h: 28,
    priceEUR: 620,
    sold: false,
    featured: true,
    img: "https://images.saatchiart.com/saatchi/1503227/art/11571153/10633399-SWOIHCMJ-7.jpg",
    desc: "Sitges. Seis y media. Antes de que llegue el calor.",
  },
  {
    id: "ac-004",
    title: "Habitación azul",
    series: "Interiores",
    year: 2023,
    category: "acrilico",
    technique: "Acrílico sobre lienzo",
    w: 100, h: 120,
    priceEUR: 3200,
    sold: true,
    featured: true,
    img: "https://images.saatchiart.com/saatchi/1926125/art/13235131/12297267-YOBHISPK-7.jpg",
    desc: "Una habitación vacía recordada. El azul, el color del recuerdo.",
  },
  {
    id: "o-005",
    title: "Limón y vaso",
    series: "Naturaleza muerta",
    year: 2024,
    category: "oleo",
    technique: "Óleo sobre tabla",
    w: 30, h: 40,
    priceEUR: 950,
    sold: false,
    featured: true,
    img: "https://images.saatchiart.com/saatchi/2068531/art/12006485/11068711-LFYRYHAJ-7.jpg",
    desc: "Un instante olvidado en la mesa de la cocina. El amarillo, contra el blanco.",
  },
  {
    id: "t-006",
    title: "Trazos de árbol",
    series: "Jardín",
    year: 2024,
    category: "tinta",
    technique: "Tinta sumi sobre papel",
    w: 50, h: 65,
    priceEUR: 480,
    sold: false,
    featured: true,
    img: "https://images.saatchiart.com/saatchi/1921557/art/13453289/12515423-PQXAFVEE-7.jpg",
    desc: "Tronco de un solo gesto. Las hojas se dispersan.",
  },
  {
    id: "c-007",
    title: "Manos — Estudio",
    series: "Retratos",
    year: 2022,
    category: "carboncillo",
    technique: "Carboncillo sobre papel",
    w: 30, h: 42,
    priceEUR: 380,
    sold: false,
    featured: false,
    img: "https://images.saatchiart.com/saatchi/677254/art/9137051/8200215-NFAMVNML-7.jpg",
    desc: "Las manos de mi padre — sólo pude dibujarlas cuando yo también empecé a envejecer.",
  },
  {
    id: "a-008",
    title: "Después de la lluvia",
    series: "Cuaderno de costa",
    year: 2024,
    category: "acuarela",
    technique: "Acuarela sobre papel de algodón",
    w: 28, h: 38,
    priceEUR: 540,
    sold: false,
    featured: false,
    img: "https://images.saatchiart.com/saatchi/2652311/art/13282053/12344187-LZQRYXGQ-7.jpg",
    desc: "El acuerdo entre el agua y el papel. Poca intervención, mucha escucha.",
  },
  {
    id: "d-009",
    title: "Umbral III",
    series: "Umbrales",
    year: 2025,
    category: "digital",
    technique: "Digital, edición limitada (1/8)",
    w: 60, h: 80,
    priceEUR: 720,
    sold: false,
    featured: false,
    img: "https://images.saatchiart.com/saatchi/1788689/art/12213773/11275971-YYNWJVTR-7.jpg",
    desc: "Formas que se repiten, ritmo roto.",
  },
  {
    id: "ac-010",
    title: "Bajada a la playa",
    series: "Interiores",
    year: 2023,
    category: "acrilico",
    technique: "Acrílico sobre lienzo",
    w: 90, h: 70,
    priceEUR: 2100,
    sold: false,
    featured: false,
    img: "https://images.saatchiart.com/saatchi/286282/art/3008742/2078635-HSC00002-7.jpg",
    desc: "Más que el recuerdo de unas vacaciones, las coordenadas de una añoranza.",
  },
  {
    id: "o-011",
    title: "Taller — Pared norte",
    series: "Notas de taller",
    year: 2024,
    category: "oleo",
    technique: "Óleo sobre lino",
    w: 70, h: 90,
    priceEUR: 2750,
    sold: false,
    featured: false,
    img: "https://images.saatchiart.com/saatchi/2009115/art/13606773/12668861-TYODWLBW-7.jpg",
    desc: "La pared que miro cada mañana, lo primero.",
  },
  {
    id: "t-012",
    title: "Bandada",
    series: "Jardín",
    year: 2023,
    category: "tinta",
    technique: "Tinta y pincel sobre papel",
    w: 65, h: 45,
    priceEUR: 520,
    sold: true,
    featured: false,
    img: "https://images.saatchiart.com/saatchi/2350685/art/13100003/12162141-UFCFUFYY-7.jpg",
    desc: "Atardecer, tres minutos. Después, la oscuridad.",
  },
  {
    id: "c-013",
    title: "Autorretrato, marzo",
    series: "Retratos",
    year: 2025,
    category: "carboncillo",
    technique: "Grafito sobre papel",
    w: 40, h: 50,
    priceEUR: 680,
    sold: false,
    featured: false,
    img: "https://images.saatchiart.com/saatchi/1466415/art/7461825/6530869-WOVHEWGO-7.jpg",
    desc: "Sin mirar al espejo, de memoria.",
  },
  {
    id: "a-014",
    title: "Jardín de limones",
    series: "Cuaderno de costa",
    year: 2023,
    category: "acuarela",
    technique: "Acuarela y gouache sobre papel de algodón",
    w: 35, h: 50,
    priceEUR: 590,
    sold: false,
    featured: false,
    img: "https://images.saatchiart.com/saatchi/313699/art/9163271/8226423-PVHNYSGU-7.jpg",
    desc: "Mediados de mayo. El amarillo, aún sin madurar.",
  },
  {
    id: "d-015",
    title: "Umbral VII",
    series: "Umbrales",
    year: 2025,
    category: "digital",
    technique: "Digital, edición limitada (3/8)",
    w: 60, h: 80,
    priceEUR: 720,
    sold: false,
    featured: false,
    img: "https://images.saatchiart.com/saatchi/2922257/art/13577647/12639739-LJLUKXBB-7.jpg",
    desc: "La misma puerta, a otra hora.",
  },
  {
    id: "ac-016",
    title: "Estudio del silencio",
    series: "Interiores",
    year: 2024,
    category: "acrilico",
    technique: "Acrílico y pigmento sobre lienzo",
    w: 80, h: 80,
    priceEUR: 1850,
    sold: false,
    featured: false,
    img: "https://images.saatchiart.com/saatchi/2851353/art/13174669/12236805-NOHMSETV-7.jpg",
    desc: "Formato cuadrado, ejercicio de equilibrio.",
  },
  {
    id: "o-017",
    title: "Silla vacía",
    series: "Notas de taller",
    year: 2023,
    category: "oleo",
    technique: "Óleo sobre lienzo",
    w: 50, h: 70,
    priceEUR: 1450,
    sold: false,
    featured: false,
    img: "https://images.saatchiart.com/saatchi/313699/art/8266008/7331182-HSC00001-7.jpg",
    desc: "La ausencia de un objeto dice más que su presencia.",
  },
  {
    id: "t-018",
    title: "Tres líneas",
    series: "Jardín",
    year: 2024,
    category: "tinta",
    technique: "Tinta sobre papel",
    w: 25, h: 35,
    priceEUR: 290,
    sold: false,
    featured: false,
    img: "https://images.saatchiart.com/saatchi/1714489/art/10609711/9672201-VCMASVHD-7.jpg",
    desc: "Lo suficiente.",
  },
];

window.CATEGORIES = [
  { id: "all", label: "Todas" },
  { id: "oleo", label: "Óleo" },
  { id: "carboncillo", label: "Carboncillo" },
  { id: "acuarela", label: "Acuarela" },
  { id: "acrilico", label: "Acrílico" },
  { id: "tinta", label: "Tinta" },
  { id: "digital", label: "Digital" },
];

window.SERIES = ["Notas de taller", "Retratos", "Cuaderno de costa", "Interiores", "Jardín", "Umbrales"];

window.SIZE_BUCKETS = [
  { id: "all", label: "Cualquier tamaño", min: 0, max: 9999 },
  { id: "s",   label: "Pequeño · < 40cm",   min: 0,  max: 40 },
  { id: "m",   label: "Medio · 40–70cm",    min: 40, max: 70 },
  { id: "l",   label: "Grande · > 70cm",    min: 70, max: 9999 },
];

window.fmtPrice = (eur) => "€" + Math.round(eur).toLocaleString("de-DE");
window.fmtSize = (w, h) => `${w} × ${h} cm`;

// Categorías helpers
window.catLabel = (id) => (window.CATEGORIES.find(c => c.id === id) || {}).label || id;
